<?php
/**
 * Fastlane payment method form.
 *
 * @var $this Bold_CheckoutPaymentBooster_Block_Payment_Form_Fastlane
 */
?>
<script type='text/javascript'>
    /**
     * Bold fastlane payment component.
     */
    const BoldFastlane = Class.create({
        emailField: document.getElementById('billing:email'),
        gatewayData: <?php echo $this->getGatewayData(); ?>,
        paymentContainerId: 'payment_form_bold_fastlane',
        isAvailable: <?php echo $this->isAvailable(); ?>,
        fastlanePaymentComponent: null,
        paymentToken: null,
        paymentCheckbox: null,
        billingAddressForm: null,
        billingAddressFieldsMap: {
            'firstname': 'billing:firstname',
            'email': 'billing:email',
            'lastname': 'billing:lastname',
            'company': 'billing:company',
            'telephone': 'billing:telephone',
            'street1': 'billing:street1',
            'street2': 'billing:street2',
            'city': 'billing:city',
            'region_id': 'billing:region_id',
            'country_id': 'billing:country_id',
            'postcode': 'billing:postcode'
        },
        shippingAddressFieldsMap: {
            'firstname': 'shipping:firstname',
            'lastname': 'shipping:lastname',
            'company': 'shipping:company',
            'telephone': 'shipping:telephone',
            'street1': 'shipping:street1',
            'street2': 'shipping:street2',
            'city': 'shipping:city',
            'region_id': 'shipping:region_id',
            'country_id': 'shipping:country_id',
            'postcode': 'shipping:postcode'
        },
        /**
         * Initialize Fastlane instance, authorize email, subscribe to email changes.
         */
        initialize: async function () {
            if (!this.isAvailable) {
                return;
            }
            if (!window.bold) {
                window.bold = {};
            }
            if (!window.bold.fastlane) {
                window.bold.fastlane = {
                    instance: null
                };
            }
            this.paymentCheckbox = document.getElementById('p_method_bold_fastlane');
            this.billingAddressForm = document.getElementById('billing-new-address-form');
            await this.buildFastlaneInstance()
            await this.authorize();
            this.subscribeToEmailChanges();
            await this.renderPaymentComponent();
            if (this.paymentCheckbox) {
                this.paymentCheckbox.addEventListener('change', async () => {
                    await this.renderPaymentComponent();
                });
            }
            this.waitForCheckoutInitialization();
            this.waitForPaymentInitialization();
        },
        waitForCheckoutInitialization: function () {
            const intervalId = setInterval(() => {
                if (typeof checkout !== 'undefined' && checkout.save) {
                    console.log('Fastlane. Checkout is initialized.');
                    this.wrapCheckoutSave();
                    clearInterval(intervalId);
                }
            }, 100);
            setTimeout(() => {
                clearInterval(intervalId);
                console.log('Fastlane. Stopped waiting for checkout to initialize.');
            }, 10000);
        },
        waitForPaymentInitialization: function () {
            const intervalId = setInterval(() => {
                if (typeof payment !== 'undefined' && payment.save) {
                    console.log('Fastlane. Payment is initialized.');
                    this.wrapPaymentSave();
                    clearInterval(intervalId);
                }
            }, 100);
            setTimeout(() => {
                clearInterval(intervalId);
                console.log('Fastlane. Stopped waiting for payment to initialize.');
            }, 10000);
        },
        /**
         * Wrap payment save method to get PayPal token first.
         *
         * @return {void}
         */
        wrapPaymentSave: function () {
            payment.save = payment.save.wrap(
                function (paymentSaveMethod) {
                    debugger;
                    if (!this.paymentCheckbox) {
                        return paymentSaveMethod();
                    }
                    if (!this.paymentCheckbox.checked) {
                        return paymentSaveMethod();
                    }
                    if (!this.paymentToken) {
                        console.log('Get Fastlane payment token...');
                        this.fastlanePaymentComponent.getPaymentToken().then((token) => {
                            console.log('Fastlane payment token:', token);
                            this.paymentToken = token;

                            const paymentForm = document.getElementById(payment.form);
                            if (paymentForm) {
                                const hiddenInput = document.createElement('input');
                                hiddenInput.type = 'hidden';
                                hiddenInput.name = 'payment[token]';
                                hiddenInput.value = token.id;
                                paymentForm.appendChild(hiddenInput);
                            }
                            this.setAddress(token.paymentSource.card.billingAddress);
                            return paymentSaveMethod();
                        }).catch(() => {
                            console.log('Failed to get Fastlane payment token.');
                            return false;
                        })
                    } else {
                        return paymentSaveMethod();
                    }
                }.bind(this)
            );
        },
        /**
         * Wrap checkout save method to process order on Bold side first.
         *
         * @return {void}
         */
        wrapCheckoutSave: function () {
            checkout.save = checkout.save.wrap(
                function (checkoutSaveMethod) {
                    debugger;
                    if (!this.paymentCheckbox) {
                        return checkoutSaveMethod();
                    }
                    if (!this.paymentCheckbox.checked) {
                        return checkoutSaveMethod();
                    }
                    if (!this.paymentToken) {
                        console.log('Get Fastlane payment token...');
                        this.fastlanePaymentComponent.getPaymentToken().then((token) => {
                            console.log('Fastlane payment token:', token);
                            this.paymentToken = token;
                            this.setAddress(token.paymentSource.card.billingAddress);
                            console.log('Process order on Bold side...');
                            //todo: add bold process order calls here.
                            return checkoutSaveMethod();
                        }).catch(() => {
                            return false;
                        })
                    } else {
                        console.log('Process order on Bold side...');
                        //todo: add bold process order calls here.
                        return checkoutSaveMethod();
                    }
                }.bind(this)
            );
        },
        /**
         * Build Fastlane Instance considering gateway type.
         *
         * @return {Promise<void>}
         */
        buildFastlaneInstance: async function () {
            if (window.bold.fastlane.instance) {
                return;
            }
            console.log('Build Fastlane Instance');
            if (this.gatewayData.is_test_mode) {
                window.localStorage.setItem('axoEnv', 'sandbox');
                window.localStorage.setItem('fastlaneEnv', 'sandbox');
            }
            if (this.gatewayData.type === 'braintree') {
                await this.buildBraintreeFastlaneInstance();
            }
        },
        /**
         * Build Fastlane Instance for the Braintree.
         *
         * @return {Promise<void>}
         */
        buildBraintreeFastlaneInstance: async function () {
            await this.loadScript(
                'https://js.braintreegateway.com/web/3.101.0-fastlane-beta.7.2/js/client.min.js'
            );
            await this.loadScript(
                'https://js.braintreegateway.com/web/3.101.0-fastlane-beta.7.2/js/data-collector.min.js'
            );
            await this.loadScript(
                'https://js.braintreegateway.com/web/3.101.0-fastlane-beta.7.2/js/hosted-fields.min.js'
            );
            await this.loadScript(
                'https://js.braintreegateway.com/web/3.101.0-fastlane-beta.7.2/js/fastlane.min.js'
            );
            const clientInstance = await window.braintree.client.create({
                authorization: this.gatewayData.client_token,
            });
            const dataCollectorInstance = await window.braintree.dataCollector.create(
                {
                    client: clientInstance,
                }
            );
            const {deviceData} = dataCollectorInstance;
            window.bold.fastlane.instance = await window.braintree.fastlane.create({
                authorization: this.gatewayData.client_token,
                client: clientInstance,
                deviceData,
                styles: {},
            });
        },
        /**
         * Load given script with attributes.
         *
         * @param {string} src
         * @param {{}} attributes
         * @return {Promise<unknown>}
         */
        loadScript: async function (src, attributes = {}) {
            return new Promise((resolve, reject) => {
                const script = document.createElement('script');
                script.src = src;
                script.async = true;
                script.onload = resolve;
                script.onerror = reject;
                if (attributes.constructor === Object) {
                    Object.keys(attributes).forEach((key) => {
                        script.setAttribute(key, attributes[key]);
                    });
                }
                document.head.appendChild(script);
            });
        },
        /**
         * Render Fastlane watermark component.
         *
         * @param watermarkContainerId
         * @param afterElement
         * @return {void}
         */
        renderWatermarkComponent: function (watermarkContainerId, afterElement) {
            const watermarkContainer = document.createElement('div');
            watermarkContainer.id = watermarkContainerId;

            const watermarkContainerImg = document.createElement('img');
            watermarkContainerImg.src = 'https://www.paypalobjects.com/connect-boba/assets/FastLaneLogoSmall.svg';
            watermarkContainerImg.alt = '';
            watermarkContainer.appendChild(watermarkContainerImg);

            afterElement.insertAdjacentElement('afterend', watermarkContainer);

            window.bold.fastlane.instance.FastlaneWatermarkComponent({
                includeAdditionalInfo: true
            }).then((WatermarkComponent) => {
                WatermarkComponent.render('#' + watermarkContainerId);
            });
        },
        /**
         * Select payment method.
         *
         * @return {void}
         */
        selectPaymentMethod: function () {
            if (this.paymentCheckbox && window.bold.fastlane.memberAuthenticated === true) {
                this.paymentCheckbox.checked = true;
            }
        },
        /**
         * Subscribe to email field changes and authorize customer with latest email field value.
         *
         * @return {void}
         */
        subscribeToEmailChanges: function () {
            if (this.emailField) {
                this.renderWatermarkComponent('fastlane-email-watermark-container', this.emailField)
                this.emailField.observe('change', () => {
                    setTimeout(async () => {
                        await this.authorize();
                    }, 500);
                });
            }
        },
        /**
         * Authorize user with email.
         *
         * @return {Promise<void>}
         */
        authorize: async function () {
            if (!this.emailField || !this.emailField.value) {
                return;
            }
            if (!window.Validation.validate(this.emailField)) {
                return;
            }
            if (window.bold.fastlane.authorizedEmail === this.emailField.value) {
                return;
            }
            window.bold.fastlane.authorizedEmail = this.emailField.value;
            console.log('Trying to authorize with email: ', this.emailField.value);
            try {
                const {identity} = window.bold.fastlane.instance;
                const {customerContextId} = await identity.lookupCustomerByEmail(this.emailField.value);
                if (customerContextId) {
                    const {
                        authenticationState,
                        profileData
                    } = await identity.triggerAuthenticationFlow(customerContextId);
                    if (authenticationState === 'succeeded') {
                        window.bold.fastlane.memberAuthenticated = true;
                        console.log('Authorized with profile Data:', profileData);
                        if (profileData.shippingAddress) {
                            this.setAddress(profileData.shippingAddress);
                            this.addUpdateAddressButton();
                        }
                    }
                    return;
                }
                window.bold.fastlane.memberAuthenticated = false;
            } catch (error) {
                console.error('Error:', error);
            }
        },
        /**
         * Set Fastlane shipping address as Magento shipping address.
         *
         * @param {{}} fastlaneAddress
         * @return {void}
         */
        setAddress: function (fastlaneAddress) {
            const magentoAddress = this.convertFastlaneAddressToMagentoAddress(fastlaneAddress);
            console.log('Set billing address...');
            console.log('Fastlane address:', fastlaneAddress);
            console.log('Magento address:', magentoAddress);
            Object.keys(this.billingAddressFieldsMap).forEach((field) => {
                if (magentoAddress[field] && document.getElementById(this.billingAddressFieldsMap[field])) {
                    document.getElementById(this.billingAddressFieldsMap[field]).value = magentoAddress[field];
                }
            });
        },
        /**
         * Add update address button to the billing address form.
         *
         * @return {void}
         */
        addUpdateAddressButton: function () {
            const fastlaneAddressContainerId = 'fastlane-address-container';
            // remove the existing button container
            const addressButtonContainer = document.getElementById(fastlaneAddressContainerId);
            if (addressButtonContainer) {
                addressButtonContainer.remove();
            }

            const fastlaneAddressContainer = document.createElement('fieldset');
            fastlaneAddressContainer.id = fastlaneAddressContainerId;
            fastlaneAddressContainer.style = '<?php echo $this->getAddressContainerStyle(); ?>';

            const updateAddressButton = document.createElement('button');
            updateAddressButton.type = 'button';
            updateAddressButton.className = 'button';
            updateAddressButton.innerHTML = 'Change Address';
            updateAddressButton.addEventListener('click', () => {
                window.bold.fastlane.instance.profile.showShippingAddressSelector().then((editAddressResult) => {
                    if (!editAddressResult.selectionChanged) {
                        return;
                    }
                    this.setAddress(editAddressResult.selectedAddress);
                });
            });
            fastlaneAddressContainer.appendChild(updateAddressButton);
            if (this.billingAddressForm) {
                this.billingAddressForm.appendChild(fastlaneAddressContainer);
            }
            this.renderWatermarkComponent('fastlane-address-watermark', updateAddressButton);
        },
        /**
         * Convert Fastlane address to Magento address.
         *
         * @param fastlaneAddress
         * @return {{}}
         */
        convertFastlaneAddressToMagentoAddress: function (fastlaneAddress) {
            let magentoAddressRegionId = null;
            if (window.billingRegionUpdater.regions[fastlaneAddress.countryCodeAlpha2]) {
                Object.entries(window.billingRegionUpdater.regions[fastlaneAddress.countryCodeAlpha2]).each((region) => {
                    const [regionId, regionData] = region;
                    if (regionData.code === fastlaneAddress.region) {
                        magentoAddressRegionId = regionId;
                    }
                })
            }
            return {
                'firstname': fastlaneAddress.firstName,
                'lastname': fastlaneAddress.lastName,
                'company': fastlaneAddress.company,
                'telephone': fastlaneAddress.phoneNumber,
                'street1': fastlaneAddress.streetAddress,
                'street2': fastlaneAddress.extendedAddress || '',
                'city': fastlaneAddress.locality,
                'region_id': magentoAddressRegionId,
                'postcode': fastlaneAddress.postalCode,
                'country_id': fastlaneAddress.countryCodeAlpha2,
            };
        },
        getShippingAddress: function () {
            let magentoAddress = {};
            Object.entries(this.shippingAddressFieldsMap).forEach((entry) => {
                const [key, idSelector] = entry;
                magentoAddress[key] = document.getElementById(idSelector)
                    ? document.getElementById(idSelector).value
                    : '';
            });
            let regionCode = '';
            if (window.shippingRegionUpdater.regions[magentoAddress.country_id]) {
                Object.entries(window.shippingRegionUpdater.regions[magentoAddress.country_id]).forEach((entry) => {
                    const [regionId, regionData] = entry;
                    if (regionId === magentoAddress.region_id) {
                        regionCode = regionData.code;
                    }
                });
            }
            return {
                'firstName': magentoAddress.firstname,
                'lastName': magentoAddress.lastname,
                'company': magentoAddress.company,
                'phoneNumber': magentoAddress.telephone,
                'streetAddress': magentoAddress.street1,
                'extendedAddress': magentoAddress.street2,
                'locality': magentoAddress.city,
                'region': regionCode,
                'postalCode': magentoAddress.postcode,
                'countryCodeAlpha2': magentoAddress.country_id,
            };
        },
        /**
         * Render Fastlane payment component.
         *
         * @return {Promise<void>}
         */
        renderPaymentComponent: async function () {
            this.selectPaymentMethod();
            const paymentContainer = document.getElementById(this.paymentContainerId);
            if (paymentContainer && this.paymentCheckbox && this.paymentCheckbox.checked) {
                const telephone = document.getElementById(this.billingAddressFieldsMap.telephone).value ?? '';
                const fields = {
                    phoneNumber: {
                        prefill: telephone
                    }
                };
                const styles = {}; //todo: add styles.
                console.log('Render Fastlane Payment Component');
                if (this.fastlanePaymentComponent === null) {
                    this.fastlanePaymentComponent = await window.bold.fastlane.instance.FastlanePaymentComponent(
                        {
                            fields,
                            styles
                        }
                    );
                }
                const shippingAddress = this.getShippingAddress();
                if (shippingAddress) {
                    console.log('Set Fastlane shipping address: ', shippingAddress);
                    this.fastlanePaymentComponent.setShippingAddress(shippingAddress);
                }
                await this.fastlanePaymentComponent.render(`#${this.paymentContainerId}`);
                return;
            }
            if (this.paymentCheckbox && this.paymentCheckbox.checked) {
                const paymentContainer = document.createElement('div');
                paymentContainer.id = this.paymentContainerId;
                const dd = this.paymentCheckbox.parentElement.nextElementSibling;
                if (dd) {
                    dd.appendChild(
                        paymentContainer
                    );
                    await this.renderPaymentComponent();
                }
            }
        }
    });
    if (!window.boldFastlaneInstance) {
        window.boldFastlaneInstance = new BoldFastlane();
    } else {
        window.boldFastlaneInstance.initialize();
    }
</script>
