<?php
/**
 * Fastlane payment method form.
 *
 * @param $this Bold_CheckoutPaymentBooster_Block_Payment_Form_Fastlane
 */
?>
<script type='text/javascript'>
    /**
     * Bold fastlane payment component.
     */
    const BoldFastlane = Class.create({
        emailField: document.getElementById('billing:email'),
        gatewayData: <?php echo $this->getGatewayData(); ?>,
        paymentContainerId: 'payment_form_bold_fastlane',
        isCustomerLoggedIn: <?php echo $this->isCustomerLoggedIn(); ?>,
        paymentCheckbox: null,
        billingAddressForm: null,
        addressFieldsMap: {
            'firstname': 'billing:firstname',
            'email': 'billing:email',
            'lastname': 'billing:lastname',
            'company': 'billing:company',
            'telephone': 'billing:telephone',
            'street1': 'billing:street1',
            'street2': 'billing:street2',
            'city': 'billing:city',
            'region_id': 'billing:region_id',
            'country_id': 'billing:country_id',
            'postcode': 'billing:postcode'
        },
        /**
         * Initialize Fastlane instance, authorize email, subscribe to email changes.
         */
        initialize: async function () {
            if (this.isCustomerLoggedIn) {
                return;
            }
            if (!window.bold) {
                window.bold = {};
            }
            if (!window.bold.fastlane) {
                window.bold.fastlane = {
                    instance: null
                };
            }
            this.paymentCheckbox = document.getElementById('p_method_bold_fastlane');
            this.billingAddressForm = document.getElementById('billing-new-address-form');
            await this.buildFastlaneInstance()
            await this.authorize();
            this.subscribeToEmailChanges();
            await this.renderPaymentComponent();
            if (this.paymentCheckbox) {
                this.paymentCheckbox.addEventListener('change', async () => {
                    await this.renderPaymentComponent();
                });
            }
        },
        /**
         * Build Fastlane Instance considering gateway type.
         *
         * @return {Promise<void>}
         */
        buildFastlaneInstance: async function () {
            if (window.bold.fastlane.instance) {
                return;
            }
            console.log('Build Fastlane Instance');
            if (this.gatewayData.is_test_mode) {
                window.localStorage.setItem('axoEnv', 'sandbox');
                window.localStorage.setItem('fastlaneEnv', 'sandbox');
            }
            if (this.gatewayData.type === 'braintree') {
                await this.buildBraintreeFastlaneInstance();
            }
        },
        /**
         * Build Fastlane Instance for the Braintree.
         *
         * @return {Promise<void>}
         */
        buildBraintreeFastlaneInstance: async function () {
            await this.loadScript(
                'https://js.braintreegateway.com/web/3.101.0-fastlane-beta.7.2/js/client.min.js'
            );
            await this.loadScript(
                'https://js.braintreegateway.com/web/3.101.0-fastlane-beta.7.2/js/data-collector.min.js'
            );
            await this.loadScript(
                'https://js.braintreegateway.com/web/3.101.0-fastlane-beta.7.2/js/hosted-fields.min.js'
            );
            await this.loadScript(
                'https://js.braintreegateway.com/web/3.101.0-fastlane-beta.7.2/js/fastlane.min.js'
            );
            const clientInstance = await window.braintree.client.create({
                authorization: this.gatewayData.client_token,
            });
            const dataCollectorInstance = await window.braintree.dataCollector.create(
                {
                    client: clientInstance,
                }
            );
            const {deviceData} = dataCollectorInstance;
            window.bold.fastlane.instance = await window.braintree.fastlane.create({
                authorization: this.gatewayData.client_token,
                client: clientInstance,
                deviceData,
                styles: {},
            });
        },
        /**
         * Load given script with attributes.
         *
         * @param {string} src
         * @param {{}} attributes
         * @return {Promise<unknown>}
         */
        loadScript: async function (src, attributes = {}) {
            return new Promise((resolve, reject) => {
                const script = document.createElement('script');
                script.src = src;
                script.async = true;
                script.onload = resolve;
                script.onerror = reject;
                if (attributes.constructor === Object) {
                    Object.keys(attributes).forEach((key) => {
                        script.setAttribute(key, attributes[key]);
                    });
                }
                document.head.appendChild(script);
            });
        },
        /**
         * Render Fastlane watermark component.
         *
         * @param watermarkContainerId
         * @param afterElement
         * @return {void}
         */
        renderWatermarkComponent: function (watermarkContainerId, afterElement) {
            const watermarkContainer = document.createElement('div');
            watermarkContainer.id = watermarkContainerId;

            const watermarkContainerImg = document.createElement('img');
            watermarkContainerImg.src = 'https://www.paypalobjects.com/connect-boba/assets/FastLaneLogoSmall.svg';
            watermarkContainerImg.alt = '';
            watermarkContainer.appendChild(watermarkContainerImg);

            afterElement.insertAdjacentElement('afterend', watermarkContainer);

            window.bold.fastlane.instance.FastlaneWatermarkComponent({
                includeAdditionalInfo: true
            }).then((WatermarkComponent) => {
                WatermarkComponent.render('#' + watermarkContainerId);
            });
        },
        /**
         * Subscribe to email field changes and authorize customer with latest email field value.
         *
         * @return {void}
         */
        subscribeToEmailChanges: function () {
            if (this.emailField) {
                this.renderWatermarkComponent('fastlane-email-watermark-container', this.emailField)
                this.emailField.observe('change', () => {
                    setTimeout(async () => {
                        await this.authorize();
                    }, 500);
                });
            }
        },
        /**
         * Authorize user with email.
         *
         * @return {Promise<void>}
         */
        authorize: async function () {
            if (!this.emailField || !this.emailField.value) {
                return;
            }
            if (!window.Validation.validate(this.emailField)) {
                return;
            }
            if (window.bold.fastlane.authorizedEmail === this.emailField.value) {
                return;
            }
            window.bold.fastlane.authorizedEmail = this.emailField.value;
            console.log('Trying to authorize with email: ', this.emailField.value);
            try {
                const {identity} = window.bold.fastlane.instance;
                const {customerContextId} = await identity.lookupCustomerByEmail(this.emailField.value);
                if (customerContextId) {
                    const {
                        authenticationState,
                        profileData
                    } = await identity.triggerAuthenticationFlow(customerContextId);
                    if (authenticationState === 'succeeded') {
                        window.bold.fastlane.memberAuthenticated = true;
                        window.bold.fastlane.profileData = profileData;
                        console.log('Authorized with profile Data:', profileData);
                        if (profileData.shippingAddress) {
                            this.setShippingAddress(profileData.shippingAddress);
                            this.addUpdateAddressButton();
                        }
                    }
                    return;
                }
                window.bold.fastlane.memberAuthenticated = false;
            } catch (error) {
                console.error('Error:', error);
            }
        },
        /**
         * Set Fastlane shipping address as Magento shipping address.
         *
         * @param {{}} fastlaneAddress
         * @return {void}
         */
        setShippingAddress: function (fastlaneAddress) {
            const magentoAddress = this.convertFastlaneAddressToMagentoAddress(fastlaneAddress);
            window.bold.fastlane.shippingAddress = fastlaneAddress;
            console.log('Fastlane address:', fastlaneAddress);
            console.log('Magento address:', magentoAddress);
            console.log('Set shipping address');
            Object.keys(this.addressFieldsMap).forEach((field) => {
                if (magentoAddress[field]) {
                    if (field === 'region_id') {
                        if (window.billingRegionUpdater) {
                            if (window.billingRegionUpdater.regions[magentoAddress.country_id]) {
                                Object.entries(window.billingRegionUpdater.regions[magentoAddress.country_id]).each((region) => {
                                    if (region[1].code === magentoAddress.region_id) {
                                        document.getElementById(this.addressFieldsMap[field]).value = region[0];
                                    }
                                })
                            }
                        }
                        return;
                    }
                    document.getElementById(this.addressFieldsMap[field]).value = magentoAddress[field];
                }
            });
        },
        /**
         * Add update address button to the billing address form.
         *
         * @return {void}
         */
        addUpdateAddressButton: function () {
            const fastlaneAddressContainerId = 'fastlane-address-container';
            // remove the existing button container
            const addressButtonContainer = document.getElementById(fastlaneAddressContainerId);
            if (addressButtonContainer) {
                addressButtonContainer.remove();
            }

            const fastlaneAddressContainer = document.createElement('fieldset');
            fastlaneAddressContainer.id = fastlaneAddressContainerId;
            fastlaneAddressContainer.style = '<?php echo $this->getAddressContainerStyle(); ?>';

            const updateAddressButton = document.createElement('button');
            updateAddressButton.type = 'button';
            updateAddressButton.className = 'button';
            updateAddressButton.innerHTML = 'Change Address';
            updateAddressButton.addEventListener('click', () => {
                window.bold.fastlane.instance.profile.showShippingAddressSelector().then((editAddressResult) => {
                    if (!editAddressResult.selectionChanged) {
                        return;
                    }
                    this.setShippingAddress(editAddressResult.selectedAddress);
                });
            });
            fastlaneAddressContainer.appendChild(updateAddressButton);
            if (this.billingAddressForm) {
                this.billingAddressForm.appendChild(fastlaneAddressContainer);
            }
            this.renderWatermarkComponent('fastlane-address-watermark', updateAddressButton);
        },
        /**
         * Convert Fastlane address to Magento address.
         *
         * @param fastlaneAddress
         * @return {{}}
         */
        convertFastlaneAddressToMagentoAddress: function (fastlaneAddress) {
            return {
                'firstname': fastlaneAddress.firstName,
                'lastname': fastlaneAddress.lastName,
                'company': fastlaneAddress.company,
                'telephone': fastlaneAddress.phoneNumber,
                'street1': fastlaneAddress.streetAddress,
                'street2': fastlaneAddress.extendedAddress || '',
                'city': fastlaneAddress.locality,
                'region_id': fastlaneAddress.region,
                'postcode': fastlaneAddress.postalCode,
                'country_id': fastlaneAddress.countryCodeAlpha2,
            };
        },
        /**
         * Render Fastlane payment component.
         *
         * @return {Promise<void>}
         */
        renderPaymentComponent: async function () {
            const paymentContainer = document.getElementById(this.paymentContainerId);
            if (paymentContainer && this.paymentCheckbox && this.paymentCheckbox.checked) {
                const telephone = window.bold.fastlane.shippingAddress.phoneNumber ?? '';
                const fields = {
                    phoneNumber: {
                        prefill: telephone
                    }
                };
                const styles = {}; //todo: add styles.
                console.log('Render Fastlane Payment Component');
                const paymentComponent = await window.bold.fastlane.instance.FastlanePaymentComponent(
                    {
                        fields,
                        styles
                    }
                );
                if (window.bold.fastlane.shippingAddress) {
                    paymentComponent.setShippingAddress(window.bold.fastlane.shippingAddress);
                }
                await paymentComponent.render(`#${this.paymentContainerId}`);
                return;
            }
            if (this.paymentCheckbox && this.paymentCheckbox.checked) {
                const paymentContainer = document.createElement('div');
                paymentContainer.id = this.paymentContainerId;
                const dd = this.paymentCheckbox.parentElement.nextElementSibling;
                if (dd) {
                    dd.appendChild(
                        paymentContainer
                    );
                    await this.renderPaymentComponent();
                }
            }
        }
    });
    if (!window.boldFastlaneInstance) {
        window.boldFastlaneInstance = new BoldFastlane();
    } else {
        window.boldFastlaneInstance.initialize();
    }
</script>
