<?php
/**
 * Bold Payments PIGI iframe template.
 *
 * @var Bold_CheckoutPaymentBooster_Block_Payment_Form_Bold $this
 */
?>
<div id="payment_form_bold">
    <div id="smart-ppcp-buttons" class="bold-ppcp-wallet-host bold-checkout-wallet-buttons"></div>
</div>
<script type="text/javascript">
    if (typeof window.bold !== 'undefined' && typeof window.bold.onBoldPaymentFormInjected === 'function') {
        window.bold.onBoldPaymentFormInjected();
    }
</script>
