<?php

/** @var Bold_CheckoutPaymentBooster_Block_Checkout_Expresspay $this */

if (!$this->isEnabled()):
    return;
endif;

$quote = $this->getQuote();
?>
<section id="<?php echo $this->getPaymentsContainerId() ?>" class="express-pay-container">
    <?php if ($this->isCheckoutActive() && $this->getPageSource() !== 'mini-cart'): ?>
    <header class="page-title">
        <h1><?php echo $this->__('Express Checkout') ?></h1>
    </header>
    <?php endif; ?>
</section>

<script type="text/javascript">
(function () {
    const expressPayConfig = {
        paymentsContainer: '<?php echo $this->getPaymentsContainerId() ?>',
        pageSource: '<?php echo $this->getPageSource() ?>',
        isFastlaneEnabled: <?php var_export($this->isFastlaneEnabled()) ?>,
        epsApiUrl: '<?php echo $this->escapeUrl($this->getEpsApiUrl()) ?>',
        epsStaticApiUrl: '<?php echo $this->escapeUrl($this->getEpsStaticApiUrl()) ?>',
        shopDomain: '<?php echo $this->jsQuoteEscape($this->getShopDomain()) ?>',
        currency: '<?php echo $this->jsQuoteEscape($this->getCurrency()) ?>',
        quoteId: '<?php echo $this->jsQuoteEscape($quote->getEntityId()) ?>',
        quoteTotals: <?php echo json_encode($this->getQuoteTotals()) ?>,
        quoteIsVirtual: <?php var_export($quote->getIsVirtual()) ?>,
        quoteItems: <?php echo json_encode($this->getQuoteItems()) ?>,
        boldCheckoutData: <?php echo json_encode($this->getBoldCheckoutData()) ?>,
        formKey: '<?php echo $this->getFormKey() ?>',
        regions: <?php echo $this->getRegionsAsJson() ?>,
        allowedCountries: <?php echo json_encode($this->getAllowedCountries()) ?>,
        defaultProductQuantity: <?php echo $this->getDefaultProductQuantity() ?>,
        productPrice: <?php echo $this->getProductPrice() ?>,
        addProductToCartUrl: '<?php echo $this->escapeUrl($this->getProductAddToCartUrl()) ?>',
        saveShippingUrl: '<?php echo $this->escapeUrl($this->getUrl('checkout/onepage/saveShipping')) ?>',
        saveShippingMethodUrl: '<?php echo $this->escapeUrl($this->getUrl('checkout/onepage/saveShippingMethod')) ?>',
        saveBillingUrl: '<?php echo $this->escapeUrl($this->getUrl('checkout/onepage/saveBilling')) ?>',
        savePaymentUrl: '<?php echo $this->escapeUrl($this->getUrl('checkout/onepage/savePayment')) ?>',
        saveOrderUrl: '<?php echo $this->escapeUrl($this->getUrl('checkout/onepage/saveOrder')) ?>',
        successUrl: '<?php echo $this->escapeUrl($this->getUrl('checkout/onepage/success')) ?>',
        createOrderUrl: '<?php echo $this->escapeUrl($this->getUrl('checkoutpaymentbooster/expresspay/createOrder')) ?>',
        updateOrderUrl: '<?php echo $this->escapeUrl($this->getUrl('checkoutpaymentbooster/expresspay/updateOrder')) ?>',
        getOrderUrl: '<?php echo $this->escapeUrl($this->getUrl('checkoutpaymentbooster/expresspay/getOrder')) ?>',
        getCartTotalsUrl: '<?php echo $this->escapeUrl($this->getUrl('checkoutpaymentbooster/index/getCartTotals')) ?>',
        getCartItemsUrl: '<?php echo $this->escapeUrl($this->getUrl('checkoutpaymentbooster/index/getCartItems')) ?>',
    };

    ExpressPay(expressPayConfig).then(async expressPay => await expressPay.render());
})();
</script>
