<?php

/** @var Bold_CheckoutPaymentBooster_Block_Checkout_Expresspay $this */

if (!$this->isEnabled()):
    return;
endif;
?>
<section id="express-pay-container">
    <header class="page-title">
        <h1><?php echo $this->__('Express Checkout') ?></h1>
    </header>
</section>

<script type="text/javascript">
    const expressPayConfig = {
        epsApiUrl: '<?php echo $this->escapeUrl($this->getEpsApiUrl()) ?>',
        epsStaticApiUrl: '<?php echo $this->escapeUrl($this->getEpsStaticApiUrl()) ?>',
        shopDomain: '<?php echo $this->jsQuoteEscape($this->getShopDomain()) ?>',
        quoteData: <?php echo json_encode($this->getQuote()->getData()) ?>,
        boldCheckoutData: <?php echo json_encode($this->getBoldCheckoutData()) ?>,
        formKey: '<?php echo $this->getFormKey() ?>',
        regions: <?php echo $this->getRegionsAsJson() ?>,
        saveShippingUrl: '<?php echo $this->escapeUrl($this->getUrl('checkout/onepage/saveShipping')) ?>',
        saveBillingUrl: '<?php echo $this->escapeUrl($this->getUrl('checkout/onepage/saveBilling')) ?>',
    };

    ExpressPay(expressPayConfig).then(async expressPay => await expressPay.render());
</script>
